filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
  - type: log
    enabled: true
    fields:
      log_source: nginx_access_log
      document_type: nginx
    paths:
      - /var/log/nginx/access.log
  - type: log
    enabled: true
    fields:
      log_source: nginx_error_log
      document_type: nginx
    paths:
      - /var/log/nginx/error.log
  - type: log
    enabled: true
    paths:
      - /var/log/qn-veinhareware-log.*.log
    fields:
      document_type: vein
    multiline.pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2}\s[0-9]{2}:[0-9]{2}:[0-9]{2}
    multiline.negate: true
    multiline.match: after

output.logstash:
  hosts: ['logstash:5044']